import { createStyles, makeStyles } from '@mui/styles';
import { Theme } from '@mui/material/styles';
export const useStyles = makeStyles((theme: Theme) =>
    createStyles({
        root: {
            width: '100%',
            flex: 1,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '0px 10px',
        },
        mainContainer: {
            width: '100%',
            height: '95%',
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
        },
        wordInfoContainer: {
            display: 'flex',
            flexDirection: 'row',
            gap: '10px',
        },
        wordDetailsContainer: {
            display: 'flex',
            flexDirection: 'column',
            width: '50%',
            gap: 25,
        },
        wordSection: {
            display: 'flex',
            flexDirection: 'row',
            gap: 10,
            alignItems: 'center',
            padding: 0,
            [theme.breakpoints.down('md')]: {
                flexDirection: 'column',
                alignItems: 'flex-start',
            },
        },
        wordText: {
            fontWeight: 'bold',
            fontSize: '24px',
            margin: 0,
        },
        addToListContainer: {
            border: '#55AD9B solid 2px',
            borderRadius: '5px',
            display: 'flex',
            padding: '4px',
            cursor: 'pointer',
            gap: '5px',
        },
        addToListText: {
            color: '#55AD9B',
        },
        levelTag: {
            borderRadius: '10px',
            padding: '5px',
            color: '#FDB911',
            border: '#FDB911 solid 1px',
            margin: 0,
            fontWeight: '500',
            fontSize: 10,
        },
        ipaText: {
            textAlign: 'left',
            fontWeight: 'bold',
            fontSize: '12px',
        },
        exampleContainer: {
            display: 'flex',
            flexDirection: 'column',
            gap: 30,
        },
        translationContainer: {
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            gap: 30,
        },
        translationText: {
            fontSize: '22px',
            fontWeight: '600',
        },
        translationIconContainer: {
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            background: '#F7DDAE',
            padding: '3px',
            borderRadius: '5px',
            height: '20px',
            width: '20px',
            boxShadow: 'rgba(99, 99, 99, 0.2) 0px 2px 8px 0px',
        },
        exampleText: {
            textAlign: 'start',
        },
        dropDownListContainer: {
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            flex: 1,
            marginBottom: '20px',
            gap: 35,
        },
        dropdownItem: {
            display: 'flex',
            flexDirection: 'row',
            cursor: 'pointer',
            gap: 10,
        },
        dropDownTitle: {
            fontWeight: 'bold',
        },
        dropdownIconContainer: {
            background: '#E5E5E5',
            borderRadius: '15px',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            height: '18px',
            width: '18px',
            boxShadow: 'rgba(99, 99, 99, 0.2) 0px 2px 8px 0px',
        },
        image: {
            width: '40%',
            [theme.breakpoints.down('md')]: {
                width: '200px',
                height: '200px',
            },
        },
        quickPracticeContainer: {
            alignItems: 'flex-start',
            display: 'flex',
            flexDirection: 'row',
            height: '300px',
        },
        quickPracticeBox: {
            width: '50%',
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'flex-start',
            gap: 3,
            [theme.breakpoints.down('md')]: {
                width: '100%',
                gap: 0,
            },
        },
        quickPracticeTitle: {
            color: '#55AD9B',
            fontWeight: 'bold',
            fontSize: '24px',
        },
        checkBtn: {
            marginLeft: 'auto',
            padding: '2px 21px',
            borderRadius: '30px',
            background: '#55AD9B',
            fontWeight: 'bold',
            color: 'white',
            cursor: 'pointer',
            fontSize: '18px',
            boxShadow: 'rgba(99, 99, 99, 0.5) 0px 4px 5px 0px',
            display: 'flex',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
        },
    }),
);
